version: '3'
#networks:
#  open5gsnetwork:
#    ipam:
#      config:
#        - subnet: 192.168.0.0/24
services:
  gnb1:
    image: ueransim:3.2.2
    container_name: gnb1
    command: 
      - gnb
    environment:
      AMF_HOSTNAME: amf
      GNB_HOSTNAME: gnb1
#    networks:
#      open5gsnetwork:
#        ipv4_address: 192.168.0.161
  gnb2:
    image: ueransim:3.2.2
    container_name: gnb2
    command: 
      - gnb
    environment:
      AMF_HOSTNAME: amf
      GNB_HOSTNAME: gnb2
#    networks:
#      open5gsnetwork:
#        ipv4_address: 192.168.0.162
  ue1:
    image: ueransim:3.2.2
    container_name: ue1
    command: 
      - ue
    cap_add:
      - all
    privileged: true
    environment:
      GNB_HOSTNAME: gnb1
      APN: internet
      MSISDN: '0000000001'
      KEY: '465B5CE8B199B49FAA5F0A2EE238A6BC'
      OP_TYPE: OPC
      OP: 'E8ED289DEBA952E4283B54E88E6183CA'
#    networks:
#      open5gsnetwork:
#        ipv4_address: 192.168.0.171
  ue2:
    image: ueransim:3.2.2
    container_name: ue2
    command: 
      - ue
    cap_add:
      - all
    privileged: true
    environment:
      GNB_HOSTNAME: gnb1
      APN: internet2
      MSISDN: '0000000002'
      KEY: '465B5CE8B199B49FAA5F0A2EE238A6BC'
      OP_TYPE: OPC
      OP: 'E8ED289DEBA952E4283B54E88E6183CA'
#    networks:
#      open5gsnetwork:
#        ipv4_address: 192.168.0.172
  ue3:
    image: ueransim:3.2.2
    container_name: ue3
    command: 
      - ue
    cap_add:
      - all
    privileged: true
    environment:
      GNB_HOSTNAME: gnb2
      APN: internet2
      MSISDN: '0000000003'
      KEY: '465B5CE8B199B49FAA5F0A2EE238A6BC'
      OP_TYPE: OPC
      OP: 'E8ED289DEBA952E4283B54E88E6183CA'
#    networks:
#      open5gsnetwork:
#        ipv4_address: 192.168.0.173
  ue4:
    image: ueransim:3.2.2
    container_name: ue4
    command: 
      - ue
    cap_add:
      - all
    privileged: true
    environment:
      GNB_HOSTNAME: gnb2
      APN: ims
      MSISDN: '0000000004'
      KEY: '465B5CE8B199B49FAA5F0A2EE238A6BC'
      OP_TYPE: OPC
      OP: 'E8ED289DEBA952E4283B54E88E6183CA'
#    networks:
#      open5gsnetwork:
#        ipv4_address: 192.168.0.174

