### For reference, see `/opt/open5gs/etc/orig/open5gs/`
amf:
  sbi:
    - addr: 192.168.0.105
      port: 7777
  ngap:
    - addr: 192.168.0.105
  guami:
    - plmn_id:
        mcc: "001"
        mnc: "01"
      amf_id:
        region: 2
        set: 1
  tai:
    - plmn_id:
        mcc: "001"
        mnc: "01"
      tac: "0001"
  plmn_support:
    - plmn_id:
        mcc: "001"
        mnc: "01"
      s_nssai:
        - sst: 1
 #         sd: 1
  security:
      integrity_order : [ NIA2, NIA1, NIA0 ]
      ciphering_order : [ NEA0, NEA1, NEA2 ]
  network_name:
      full: Open5GS
  amf_name: open5gs-amf0

nrf:
    sbi:
#      - name: nrf
      - addr: 192.168.0.110
        port: 7777

parameter:
max:
pool:
time:
