### For reference, see `/opt/open5gs/etc/orig/open5gs/`
bsf:
    sbi:
      - addr: 192.168.0.115
        port: 7777
nrf:
  sbi:
#    - name: nrf
    - addr: 192.168.0.110
      port: 7777
parameter:
max:
pool:
time:
